### ISSUE TITLE
styles transform is broken

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk-archive/bemjson-to-jsx#30]
```
({
    block: 'button',
    text: 'Hello world',
    attrs: {
        style: 'width: 200px; height: 200px;'
    }
})
```
=>
```
<button text='Hello world' style={{ 'width': ' 200px', ' height': ' 200px' }} attrs={{ 'style': { 'width': ' 200px', ' height': ' 200px' } }}/>
```

but `' height'` is not same as `'height'` the space is unwanted

**Comment by Yeti-or** [comment]
Maybe we need to drop attrs that we transfered to style prop

**Comment by zxqfox** [comment]
Close one:
```js
({ block: 'button', attrs: { 'margin-right': '5px' } })
```
//  Unsupported style property  margin-right. Did you mean  marginRight? Check the render method of `textinput`.

**Comment by Yeti-or** [comment]
forgot about close one: https://github.com/bem-sdk-archive/bemjson-to-jsx/issues/49
