### ISSUE TITLE
We need to pascaleCase tags

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk-archive/bemjson-to-jsx#43]
as it done here: 
https://github.com/Yeti-or/bemjson-to-jsx-loader/blob/master/index.js#L115

**Comment by Yeti-or** [comment]
I think this is okay:
```
const classesInseteadOfTags = function(jsx, json) {
    if (jsx.bemEntity) {
        jsx.tag = pascalCase(jsx.tag);
    }
};

```

**Comment by zxqfox** [comment]
Please pass this as a function in options.

**Comment by Yeti-or** [comment]
@zxqfox I will use `pascalCase(bemEntity.toString())` is it okay for you?
cause I need to get `BlockElem`  string
Or do you prefer  `${pascalCase(bemEntity.block)}${pascalCase(bemEntity.elem)}` ?

**Comment by zxqfox** [comment]
The second one.
